### ISSUE TITLE
Баги в EFileUploader

### ISSUE THREAD

**Issue by novkri** [egal/widget-library#104]
1. Поправить обработку ответов у запросов в EFileUploader. Т.к. раньше запросы отправлялись через axios, а не Egal, остались неработающие обработчики результатов запроса
2. После того как изображение загружено и допустима загрузка только одного файла -  остается "поле для загрузки": 
![image](https://user-images.githubusercontent.com/44196228/170910720-9dd481b2-da56-48a6-b615-5164b3dddf7a.png)
2.1. Невозможно загрузить больше 1 картинки, т.к. пропадает кнопка. Возможна загрузка только через drag&drop
3. Крашится загрузка картинки больше 5мб на uploadPart (500 ошибка)
4. Нету подписи размера файла рядом с названием

**Comment by Yulya-Yu** [comment]
@novkri :triangular_flag_on_post: 2
