### ISSUE TITLE
Подготовить виджет "Календарь"

### ISSUE THREAD

**Issue by Yulya-Yu** [egal/widget-library#12]
https://www.figma.com/file/BK3sXKYGfpchEtIJJWr1hD/Basic?node-id=579%3A23035

**Comment by novkri** [comment]
Закончено

**Comment by novkri** [comment]
@Yulya-Yu :triangular_flag_on_post: 2 За ревью и помощь

**Comment by Yulya-Yu** [comment]
@novkri 🚩 2  виджет Календарь
