### ISSUE TITLE
[ТТИТ] Вопросы, проблемы, предложения по библиотеке виджетов Egal 

### ISSUE THREAD

**Issue by Neirokin** [egal/widget-library#125]
### [ТТИТ] Вопросы, проблемы, предложения по Egal
Здесь фиксируется всё, что касается виджетов Egal. Если есть какой-то вопрос по использованию, реализации того или иного функционала, проблемы с документацией или же появилась какая-то идея по улучшению - всё это можно и даже нужно оставить здесь

**Comment by qwertygaerty** [comment]
![image](https://user-images.githubusercontent.com/54385591/174517106-a7ee9a6f-49e3-4b15-95ca-5a2f0b6576f7.png)
![image](https://user-images.githubusercontent.com/54385591/174517277-956a2869-ebc1-44f1-bdb8-7e881fa7f7cc.png)
![image](https://user-images.githubusercontent.com/54385591/174517365-79f3d5b9-93ad-4b89-ae48-c6208e508717.png)

Не работает inputMaxLength у e-input

**Comment by Yulya-Yu** [comment]
@novkri :triangular_flag_on_post: 2
