### ISSUE TITLE
Подготовить виджет графиков Pie Chart/Line Chart

### ISSUE THREAD

**Issue by Yulya-Yu** [egal/widget-library#13]
https://www.figma.com/file/BK3sXKYGfpchEtIJJWr1hD/Universal-UI-kit?node-id=853%3A16631

**Comment by novkri** [comment]
Закончено (Line Charts, Pie Charts, Curves Chart)

**Comment by Yulya-Yu** [comment]
@novkri 🚩 2 Line Charts

**Comment by Yulya-Yu** [comment]
@novkri 🚩 2 Pie Charts

**Comment by Yulya-Yu** [comment]
@novkri 🚩 2 Curves Charts

**Comment by novkri** [comment]
@Yulya-Yu :triangular_flag_on_post: 2 За ревью
