### ISSUE TITLE
EInput в консоль прилетает warns, если в объект data передать modelValue равное 0 as number

### ISSUE THREAD

**Issue by App-Ju** [egal/widget-library#145]
Если в EInput передать :data="{ modelValue: 0 }", в консоль прилетает два сообщения с предупреждением.
![Снимок экрана от 2022-07-04 16-58-12](https://user-images.githubusercontent.com/88981239/177131609-1c2567c0-37f1-4bbf-b343-29cef88d298a.png)

Вариант решения https://github.com/egal/widget-library/pull/144

**Comment by novkri** [comment]
Исправлено в PR #144 
Нужно сделать релиз чтобы обновления появились
