### ISSUE TITLE
Баг при нажатии Enter на EInput

### ISSUE THREAD

**Issue by Neirokin** [egal/widget-library#146]
Студенты столкнулись с багом, что при нажатии на Enter в любом из полей формы происходит очищение инпута. Если из DOM вырезать ClearButton, то такого бага не происходит. До конца не понял при каких условиях это происходит, но пользовались они нативной формой с использованием виджетов. 
Один из вариантов решения проблемы, это переписать v-show на v-if, однако повлияет ли это как-нибудь на остальной функционал - хз
 
![image](https://user-images.githubusercontent.com/56441777/177254623-a1617710-3f73-43ed-9318-4822a4cf7c4c.png)

**Comment by Yulya-Yu** [comment]
закрыто в [PR 146](https://github.com/egal/widget-library/pull/153)
