### ISSUE TITLE
ENavbarRight неправильно отображает логотип

### ISSUE THREAD

**Issue by Neirokin** [egal/widget-library#17]
Логотип в сайдбаре вылезает за границы в свёрнутом состоянии
![image](https://user-images.githubusercontent.com/56441777/155685968-be051612-49e2-4699-8105-e3367cf1b84d.png)
![image (3)](https://user-images.githubusercontent.com/56441777/155686580-ad953b71-20e0-45ec-b0ca-3545b6dc074b.jpg)

**Comment by Yulya-Yu** [comment]
Исправлено в релизе [v1.0.0-beta.3](https://github.com/egal/widget-library/releases/tag/v1.0.0-beta.3)
