### ISSUE TITLE
В некоторых компонентах не работают пропы

### ISSUE THREAD

**Issue by Neirokin** [egal/widget-library#18]
В некоторых компонентах не работают пропы. Например в `ECheckbox` и `EToggle` проп `checked` никак не изменяет состояние компонентов. Скорее всего это из-за того, что нативные пропы явно не прописаны в `props`

**Comment by Yulya-Yu** [comment]
Пропы в компоненты передаются не отдельно, а в объекте data, как описано в [документации](https://egal.github.io/egal-docs/#/client/widgets/checkbox).
