### ISSUE TITLE
Нет возможности добавить иконки в сайдбар

### ISSUE THREAD

**Issue by Neirokin** [egal/widget-library#19]
Для сайдбара нужно добавить возможность устанавливать иконки, вместо кружков (требование дизайна)

Сейчас:
![image](https://user-images.githubusercontent.com/56441777/155922677-42006d79-2cab-4410-a41d-1fb8c2c08d86.png)

Как должно быть:
![image](https://user-images.githubusercontent.com/56441777/155922698-08903091-8fda-4407-8650-bda403e425a6.png)

**Comment by Yulya-Yu** [comment]
Исправлено в релизе [v1.0.0-beta.3](https://github.com/egal/widget-library/releases/tag/v1.0.0-beta.3)
