### ISSUE TITLE
Сайдбар баги

### ISSUE THREAD

**Issue by Neirokin** [egal/widget-library#23]
1. Если развернуть вложенный список и свернуть меню, то останется иконка вложенной позиции. Возможно лучше будет закрывать вложенные списки перед сворачиванием сайдбара
![image](https://user-images.githubusercontent.com/56441777/156485921-1fe12e11-a9a8-4536-b417-2743f53e7f7b.png)
![image](https://user-images.githubusercontent.com/56441777/156485983-0ecc065d-e6c2-453b-8502-0f6833ac9c0f.png)

2. Название ссылок появляются до того, как сайдбар полностью откроется. Можно добавить overflow на контейнер, чтобы ссылки не вылезали из него во время открытия сайдбара

**Comment by Yulya-Yu** [comment]
@novkri triangular_flag_on_post 2 фикс багов
