### ISSUE TITLE
EPagination не работает

### ISSUE THREAD

**Issue by Neirokin** [egal/widget-library#24]
Ошибка в консоли:
![image](https://user-images.githubusercontent.com/56441777/156523715-d4aca9d7-7337-46aa-bc08-463edcd6dfd9.png)

Ошибка в source:
![image](https://user-images.githubusercontent.com/56441777/156523897-294bf670-d77e-4938-bf24-5a61b8e02a6b.png)

**Comment by Yulya-Yu** [comment]
@novkri :triangular_flag_on_post: 2 фикс багов
