### ISSUE TITLE
EInput баги

### ISSUE THREAD

**Issue by Neirokin** [egal/widget-library#26]
1. Не работает проп styleConfig. Инпут не кастомизируется
2. Цвет и ширина border не соответствует макету
Макет:
![image](https://user-images.githubusercontent.com/56441777/156699751-3042e820-f7c8-4b0c-b718-2ff1c58549aa.png)

Реализовано:
![image](https://user-images.githubusercontent.com/56441777/156699793-e9e75340-ee8a-4b41-8549-17d09747a3a2.png)

**Comment by Yulya-Yu** [comment]
закрыто в релизе [v1.0.0-beta.6](https://github.com/egal/widget-library/releases/tag/v1.0.0-beta.6)

**Comment by Yulya-Yu** [comment]
@Yulya-Yu :triangular_flag_on_post: 2

**Comment by Neirokin** [comment]
Работает, можно закрывать
