### ISSUE TITLE
Не работает EBreadcrumbs

### ISSUE THREAD

**Issue by Neirokin** [egal/widget-library#27]
Компонент виден через Vue Devtools, но на странице  не отображается. Никакой ошибки в консоль не выбрасывает

**Comment by Yulya-Yu** [comment]
@novkri :triangular_flag_on_post: 2

**Comment by Yulya-Yu** [comment]
Исправлено в релизе [v1.0.0-beta.9](https://github.com/egal/widget-library/releases/tag/v1.0.0-beta.9)

**Comment by novkri** [comment]
@Yulya-Yu :triangular_flag_on_post: 2 За помощь с компонентом

**Comment by Neirokin** [comment]
Работает, можно закрывать
