### ISSUE TITLE
Баги в виджете "Календарь"

### ISSUE THREAD

**Issue by Yulya-Yu** [egal/widget-library#31]
1. Не отображаются опции выбора времени в селектах
![Screenshot from 2022-03-09 15-08-21](https://user-images.githubusercontent.com/34450219/157399170-0f6f140e-ad8b-4200-a4ce-ba656428c2dd.png)

2. Заменить плэйсхолдеры в селектах, чтобы вписывались в маленький инпут. Например, на HH, MM, AM/PM

3. В выбранном интервале цветом не выделяются даты, не входящие в текущий месяц. Должны выделяться все даты, попадающие в интервал.
![Screenshot from 2022-03-09 15-10-51](https://user-images.githubusercontent.com/34450219/157399588-7c6a5064-8c06-494c-8bef-79d76183282f.png)

4. Поправить верстку в двойном календаре, чтобы не съезжала при смене месяцев:
![Screenshot from 2022-03-09 15-12-39](https://user-images.githubusercontent.com/34450219/157399832-ab9cde41-4c47-4f49-a666-f4ba945cb7f0.png)

5. В двойном календаре не изменяется месяц справа.

**Comment by novkri** [comment]
@Yulya-Yu  PR #32

**Comment by novkri** [comment]
все готово, все работает
