### ISSUE TITLE
EPagination: не применяются передаваемые стили номерам страниц. ESelect отображает дропдаун только снизу

### ISSUE THREAD

**Issue by novkri** [egal/widget-library#39]
1. Передаваемые стили не применяются на номера страниц (Пример: передан color: 'red', покрасились только стрелочки)
![image](https://user-images.githubusercontent.com/44196228/158116551-b4c7dd7b-2b6e-4d61-bafe-5628580821a7.png)
2. ESelect может отображать дропдуан только снизу. Соответсвенно если пагинация с селектом внизу страницы - дропдаун выходит за пределы экрана и приходится прокручивать страницу
![image](https://user-images.githubusercontent.com/44196228/158117016-ff0d6c96-24b3-493c-baee-c4fbd311411a.png)
![image](https://user-images.githubusercontent.com/44196228/158116968-c7bd24b2-0f09-451c-ad0b-b4f47f9230dd.png)

**Comment by Yulya-Yu** [comment]
Исправлено в релизе [v1.0.0-beta.8](https://github.com/egal/widget-library/releases/tag/v1.0.0-beta.8)

**Comment by Yulya-Yu** [comment]
@novkri :triangular_flag_on_post: 2
