### ISSUE TITLE
EButton: исправить приоритет стилей

### ISSUE THREAD

**Issue by novkri** [egal/widget-library#41]
Если в компоненте EButton в  `:data` передается:
`
:data="{
color: 'color_name_1',
disabled: {
 color: color_name_disabled',
}
}"
`
то в состоянии кнопки disabled - не применяется цвет color_name_disabled, остается color_name_1
      

Пример: кнопка заблочена, иконка все еще окрашена "активным" цветом
![image](https://user-images.githubusercontent.com/44196228/158119427-29934c89-c184-4b4e-8aeb-74faf45cab20.png)

**Comment by Yulya-Yu** [comment]
Исправлено в [PR](https://github.com/egal/widget-library/pull/48)

**Comment by Yulya-Yu** [comment]
@novkri :triangular_flag_on_post: 2
