### ISSUE TITLE
Улучшение sidebar

### ISSUE THREAD

**Issue by Portunis** [egal/widget-library#42]
Нужно добавить счетчик, справа от ссылки. Добавить возможность более гибко настраивать стили ссылкам.
Пример счетчика: 
![Снимок экрана от 2022-03-14 14-02-31](https://user-images.githubusercontent.com/55052382/158121183-0906ae33-d784-4112-9f14-fd3ac8833dfc.png)

1. Обновить документацию и шаблон, добавить стайл конфиг.
2. Добавить слот для пунктов меню.
3. Сложности со стилизацией компонента, подумать как решить.

**Comment by Yulya-Yu** [comment]
добавлено в [PR#55](https://github.com/egal/widget-library/pull/55)
[документация](https://docs.egal.pro/#/client/widgets/sidebar) обновлена соответственно.
