### ISSUE TITLE
При установке фокуса в Input данные внутри смещаются

### ISSUE THREAD

**Issue by Neirokin** [egal/widget-library#44]
![image](https://user-images.githubusercontent.com/56441777/158527483-5f68e6f7-13ec-4065-ae36-b64e7c70bbe7.png)
Суть в том, что при попадании инпута в фокус у него увеличивается размер border из-за чего элементы инпута начинает смещаться.  
Предлагаю при фокусе не менять размер border, а выставлять outline необходимого размера

**Comment by Yulya-Yu** [comment]
@Yulya-Yu :triangular_flag_on_post: 2
