### ISSUE TITLE
Sidebar: некорректная подсветка текущей активной ссылки и открытие вложенного списка

### ISSUE THREAD

**Issue by novkri** [egal/widget-library#46]
1. После перехода из вложенного списка на страницу с роутом "/", обе ссылки подсвечиваются как "текущие активные"
2. Не работает открытие вложенного списка по клику на всю область ссылки, нужно нажимать только на стрелочку

**Comment by Yulya-Yu** [comment]
Исправлено в релизе [v1.0.0-beta.9](https://github.com/egal/widget-library/releases/tag/v1.0.0-beta.9)

**Comment by Yulya-Yu** [comment]
@novkri :triangular_flag_on_post: 2
