### ISSUE TITLE
ESelect баги

### ISSUE THREAD

**Issue by Neirokin** [egal/widget-library#54]
1. При полной очистке селекта со свойством ``searchableInput: true``  появляется warning:
![image](https://user-images.githubusercontent.com/56441777/158965661-b48d71c5-7b36-4c0e-a0bc-b5d90ddc4b97.png)

2. Не работает свойство ``clearable: false`` в селекте со свойством ``searchableInput: true``
![image](https://user-images.githubusercontent.com/56441777/158966062-c9d75dbe-fc15-4ba4-9c85-a9df44ddd29c.png)
![image](https://user-images.githubusercontent.com/56441777/158966095-b203ab41-c8d5-44ba-934d-003b2082433c.png)

**Comment by Yulya-Yu** [comment]
@novkri :triangular_flag_on_post: 2
