### ISSUE TITLE
Module Warning в терминале

### ISSUE THREAD

**Issue by Neirokin** [egal/widget-library#66]
Жалуется на ``width:fill-available`` где-то в Navbar
![image](https://user-images.githubusercontent.com/56441777/159448155-5cc55428-abe3-421c-b8f7-f0f4b7252568.png)
![image](https://user-images.githubusercontent.com/56441777/159448487-42668a59-b30e-44e7-83f2-88fd57d6f99b.png)

**Comment by Yulya-Yu** [comment]
@novkri :triangular_flag_on_post: 2
