### ISSUE TITLE
Нужна новая функция для ESelect

### ISSUE THREAD

**Issue by Neirokin** [egal/widget-library#67]
Для ESelect нужно добавить кнопку "Показать больше" после всех опций дропдауна. Ещё нужно нужно отслеживать общее количество записей (в БД) и количество записей в дропдауне, для переключения отображения кнопки "Показать больше"
![image](https://user-images.githubusercontent.com/56441777/160070040-8998fa3a-d1ff-4aed-b19c-fdfd755a662b.png)

**Comment by Yulya-Yu** [comment]
@novkri :triangular_flag_on_post: 2

**Comment by Yulya-Yu** [comment]
Добавлено в релизе [v1.0.0-beta.14](https://github.com/egal/widget-library/releases/tag/v1.0.0-beta.14)
