### ISSUE TITLE
ESelect: Баг валидации

### ISSUE THREAD

**Issue by Neirokin** [egal/widget-library#68]
Не валидируется ESelect, когда передаёшь функции-валидаторы. В валидатор всегда приходит ``undefined``
![image](https://user-images.githubusercontent.com/56441777/160073016-952a44ba-622c-432d-a938-ef9fb3f82190.png)

**Comment by Yulya-Yu** [comment]
@novkri :triangular_flag_on_post: 2

**Comment by Yulya-Yu** [comment]
Добавлено в релизе [v1.0.0-beta.14](https://github.com/egal/widget-library/releases/tag/v1.0.0-beta.14)
