### ISSUE TITLE
Расширить возможности кастомизации лэйблов для тогглеров

### ISSUE THREAD

**Issue by Neirokin** [egal/widget-library#78]
Не хватает возможности кастомизировать состояния для лэйблов у тогглеров (конкретно для лэйбла чекбокса)
Нужно добавить такую же обработку состояний ``hover``, ``active``, ``disabled`` (а для чекбокса ещё и ``checked``)

Кейс:
![image](https://user-images.githubusercontent.com/56441777/161499479-94d95333-c5b6-42b8-86d3-511cbf848886.png)

**Comment by Yulya-Yu** [comment]
закрыто в [PR 83](https://github.com/egal/widget-library/pull/83)

**Comment by Yulya-Yu** [comment]
@novkri :triangular_flag_on_post: 2
