### ISSUE TITLE
Добавить опцию "emits" в чекбокс

### ISSUE THREAD

**Issue by Neirokin** [egal/widget-library#81]
Нужна опция ``emits``, которая описывает какие события компонент может эмитить. Без неё отправляется два события ``change``: кастомное и нативное  
  
Без ``emits``:
![image](https://user-images.githubusercontent.com/56441777/161698871-feb0a679-430e-4ac1-8c1e-6bab821dddc6.png)
  
С ``emits``:
![image](https://user-images.githubusercontent.com/56441777/161698950-d571eac2-d9da-4c24-b30a-d965e454a331.png)

**Comment by Yulya-Yu** [comment]
закрыто в [PR 83](https://github.com/egal/widget-library/pull/83)

**Comment by Yulya-Yu** [comment]
@novkri :triangular_flag_on_post: 2
