### ISSUE TITLE
ETooltip: не отображать тултип, если в него ничего не передается

### ISSUE THREAD

**Issue by novkri** [egal/widget-library#84]
1. Не отображать тултип, если в слот ничего не передается:  
 ![image](https://user-images.githubusercontent.com/44196228/162390363-87f8a50d-d957-490b-ad4e-7abf167c2fc3.png)
3. У слота с именем #element убрать лишние стили, если в слот ничего не передается: 
![image](https://user-images.githubusercontent.com/44196228/162390784-44944aff-ffcd-49ca-ba0e-011ff6c10eaf.png)

**Comment by Yulya-Yu** [comment]
@novkri :triangular_flag_on_post: 2

**Comment by Yulya-Yu** [comment]
Закрыто в [PR 86](https://github.com/egal/widget-library/pull/86)
