### ISSUE TITLE
EInput: Добавить возможность подставлять постфикс 

### ISSUE THREAD

**Issue by novkri** [egal/widget-library#85]
Добавлять как иконку справа, только текст:
![image](https://user-images.githubusercontent.com/44196228/162394203-b08e6e26-64cf-4e37-a261-bb90b28f1147.png)

**Comment by Yulya-Yu** [comment]
Закрыто в [PR 87](https://github.com/egal/widget-library/pull/87/).

**Comment by Yulya-Yu** [comment]
@novkri :triangular_flag_on_post: 2
