### ISSUE TITLE
В EFileUploader нельзя передавать текст. Сложности с интеграцией

### ISSUE THREAD

**Issue by novkri** [egal/widget-library#89]
1. Нельзя поменять текст 'Drop files here or browse file' на свой
![image](https://user-images.githubusercontent.com/44196228/163755895-369598ef-2b81-47aa-ba2b-b0018ed14ac3.png)
2. Интеграция: 
- нельзя передавать название кастомного экшена
- независимо от размера файла и их количества всегда передает запрос на /createMultipartUpload
- не подцепляется токен авторизации, из-за чего запросы на загрузку изображений для авторизованных пользователей не работают вообще

**Comment by Yulya-Yu** [comment]
закрыто в релизе [v1.0.0-beta.27](https://github.com/egal/widget-library/releases/tag/v1.0.0-beta.27)

**Comment by Yulya-Yu** [comment]
@novkri :triangular_flag_on_post: 2
